model_name: cardiffnlp/twitter-roberta-base-sentiment-latest
data_file: survey_data.csv
relevant_columns: ['course code', 'feedback', 'previous experience', 'gender', 'attendance', 
                  'course difficulty', 'study hours (per week)', 'overall satisfaction', 'department']
